### ISSUE TITLE
Selecting more tables

### ISSUE THREAD

**Issue by stiffler17** [deliciousbrains/better-search-replace#22]
I think there is a issue in the new version. When I select more tables with shift and click and execute it, the result show 1 table searched and not the quantity of selected tables.

Please check this.

**Comment by mgshaw** [comment]
Hi,

I'm not able to replicate this. Does it still show the correct number of changes (not tables)? Or are you getting any errors?

**Comment by stiffler17** [comment]
No, there are no errors. I've selected all tables with shift and so on. 
If I look the details of the testrun it shows only the first table.  
After the first pic I click execute. Afterwards it shows pic2. Pic3 is the detail view after the run.
Few days ago the plugin works but since I updated it today this issue appers.

![run1](https://cloud.githubusercontent.com/assets/14252961/9834120/61c0a270-59ad-11e5-99fa-580e93482931.png)
![run2](https://cloud.githubusercontent.com/assets/14252961/9834119/61bf3098-59ad-11e5-8750-5c967acfb80a.png)
![run3](https://cloud.githubusercontent.com/assets/14252961/9834121/61c281a8-59ad-11e5-9164-233fed4f4bb7.png)

**Comment by GaryJones** [comment]
FWIW, I'm not able to replicate this either. I select various combinations of tables with Shift, CMD, or CMD-A, and the table selection before and after the dry run is the same, and the modal shows the selected tables correctly as well.

BSR 1.3.1

**Comment by tkes** [comment]
@GaryJones Can replicate it here at a customer site, seems some hostings use different values for `arg_separator.input` and `arg_separator.output` which leads to a wrong value for `bsr_data` when it is created with `http_build_query()` default params by the plugin, more [details in this thread](https://wordpress.org/support/topic/select-all-or-multiple-tables-not-working/).

**Comment by GaryJones** [comment]
@tkes Great summary and link - that should greatly help the team to get a fix in place :-)
