### ISSUE TITLE
Changes made disappear when logging out from Wordpress

### ISSUE THREAD

**Issue by MisterXXXXX** [deliciousbrains/better-search-replace#29]
Hello, I used the Better Search Replace plugin to replace some words in my blog's articles and everything went fine, all words found in wp_options, wp_postmeta and wp_posts tables were replaced. However, when I logged out from Wordpress, all changes disappeared and the old words come out again. Tried to refresh the page, tried from another browser and another computer but same result. I did NOT use the dry mode, therefore changes were effective and, when being logged in, I could see them in every page loaded. Am using the latest Wordpress and plugin versions. Can you pls help ??

**Comment by mattgrshaw** [comment]
This sounds like a caching issue rather than an issue with BSR. You may want to double check that all of your caches have been purged and see if that fixes the issue.
