### ISSUE TITLE
Changelog for 1.3 is missing

### ISSUE THREAD

**Issue by Drugoy** [deliciousbrains/better-search-replace#34]
Subj.

**Comment by mattgrshaw** [comment]
You can find the 1.3 changelogs here-

https://wordpress.org/plugins/better-search-replace/changelog/
https://github.com/deliciousbrains/better-search-replace/blob/master/README.txt

**Comment by Drugoy** [comment]
Weird, this is how I see changelog within from site admin panel when viewing changelog (/wp-admin/plugin-install.php?tab=plugin-information&plugin=better-search-replace&section=changelog) for the suggested version:
<img src="https://i.imgur.com/o106BEP.png">
