### ISSUE TITLE
Search Replace with ampersand & causes error

### ISSUE THREAD

**Issue by inception-websites** [deliciousbrains/better-search-replace#41]
When searching for something with the "&" symbol in the title, the replace glitches and only replaces with text before the &.

**Comment by highly-irregular** [comment]
I ran into this too, except I didn't find out if the replace was glitching; instead I discovered even doing a dry run would refresh the page and the Search text would come back with the ampersand character missing, and the text after it missing too. I lost confidence in the tool to do the job at this point.

**Comment by mattgrshaw** [comment]
This has been fixed with BSR 1.3.3
